### PR TITLE
fix: install the `latest` custom Webpack package version

### LINKED ISSUE #306: custom-webpack@^11 not found
### Demonstration
Executing `npm install` just after creating the Angular 11 parcel produces the error "No matching version found for @angular-builders/custom-webpack@^11".
This is using single-spa-angular@4.8.0, after the fix from #304 .

Created the project here:
https://github.com/daniloesk/single-spa-errors/tree/single-spa-angular%23306

Command logs:
```
USER:HOME$ npx create-single-spa --dir . --moduleType app-parcel --framework angular
? Project name (can use letters, numbers, dash or underscore) ng11error
? Do you want to enforce stricter type checking and stricter bundle budgets in the workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict Yes
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE ng11error/README.md (1018 bytes)
CREATE ng11error/.editorconfig (274 bytes)
CREATE ng11error/.gitignore (631 bytes)
CREATE ng11error/angular.json (3647 bytes)
CREATE ng11error/package.json (1199 bytes)
CREATE ng11error/tsconfig.json (737 bytes)
CREATE ng11error/tslint.json (3185 bytes)
CREATE ng11error/.browserslistrc (703 bytes)
CREATE ng11error/karma.conf.js (1104 bytes)
CREATE ng11error/tsconfig.app.json (287 bytes)
CREATE ng11error/tsconfig.spec.json (333 bytes)
CREATE ng11error/src/favicon.ico (948 bytes)
CREATE ng11error/src/index.html (295 bytes)
CREATE ng11error/src/main.ts (372 bytes)
CREATE ng11error/src/polyfills.ts (2826 bytes)
CREATE ng11error/src/styles.css (80 bytes)
CREATE ng11error/src/test.ts (753 bytes)
CREATE ng11error/src/assets/.gitkeep (0 bytes)
CREATE ng11error/src/environments/environment.prod.ts (51 bytes)
CREATE ng11error/src/environments/environment.ts (662 bytes)
CREATE ng11error/src/app/app-routing.module.ts (245 bytes)
CREATE ng11error/src/app/app.module.ts (393 bytes)
CREATE ng11error/src/app/app.component.css (0 bytes)
CREATE ng11error/src/app/app.component.html (25757 bytes)
CREATE ng11error/src/app/app.component.spec.ts (1066 bytes)
CREATE ng11error/src/app/app.component.ts (213 bytes)
CREATE ng11error/e2e/protractor.conf.js (904 bytes)
CREATE ng11error/e2e/tsconfig.json (274 bytes)
CREATE ng11error/e2e/src/app.e2e-spec.ts (660 bytes)
CREATE ng11error/e2e/src/app.po.ts (274 bytes)
✔ Packages installed successfully.
    Successfully initialized git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Does your application use Angular routing? Yes
? Does your application use BrowserAnimationsModule? No
    Added 'single-spa' as a dependency
    Added 'single-spa-angular' as a dependency
    Added '@angular-builders/custom-webpack' as a dependency
    Generated 'main.single-spa.ts
    Generated 'single-spa-props.ts
    Generated asset-url.ts
    Generated extra-webpack.config.js
    Using @angular-devkit/custom-webpack builder.
    Updated angular.json configuration
    @angular-builders/custom-webpack:browser
CREATE extra-webpack.config.js (303 bytes)
CREATE src/main.single-spa.ts (933 bytes)
CREATE src/app/empty-route/empty-route.component.ts (143 bytes)
CREATE src/single-spa/asset-url.ts (502 bytes)
CREATE src/single-spa/single-spa-props.ts (333 bytes)
UPDATE package.json (1560 bytes)
UPDATE tsconfig.app.json (188 bytes)
UPDATE angular.json (3844 bytes)
For further routing setup, see https://single-spa.js.org/docs/ecosystem-angular#configure-routes
Project setup complete!
Steps to test your Angular single-spa application:
1. Run 'npm run serve:single-spa:ng11error'
2. Go to http://single-spa-playground.org/playground/instant-test?name=ng11error&url=%2F%2Flocalhost%3A4200%2Fmain.js&framework=angular to see it working!
```

```
USER:single-spa-angular-11-error$ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-builders/custom-webpack@^11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'single-spa-angular-11-error'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2020-11-23T17_21_10_478Z-debug.log
```

### Expected Behavior
`npm install` completes successfully.

### Actual Behavior
Error "No matching version found for @angular-builders/custom-webpack@^11".

### PR DESCRIPTION
**Pull request by arturovt**
Closes #306

### CODE REVIEW

**Comment by daniloesk** [comment]
It seems the workaround with latest version 10.0.1 does not work. I am gathering the data, but it should be better not to merge this. Please see #307.

File: schematics/ng-add/dependencies.ts [hunk 1]
```diff
@@ -33,16 +33,13 @@ export function getSingleSpaAngularDependency(): NodeDependency {
...
 export function getAngularBuildersCustomWebpackDependency(): NodeDependency {
-  const { VERSION } = require('@angular/core');
-
   return {
     name: '@angular-builders/custom-webpack',
-    version: `^${VERSION.major}`,
+    // Relying on the current major version of Angular is wrong.
+    // We have to install the `latest` version because we cannot know
+    // when the new version will be published.
+    version: 'latest',
```
Comment (joeldenning) [inline schematics/ng-add/dependencies.ts:42]: Does the latest version of `@angular-builders/custom-webpack` work with Angular 9 and 10?

**Review by joeldenning — COMMENTED** [review]
Thanks for your work here - one question.

File: schematics/ng-add/dependencies.ts (hunk 1 above)
Comment (arturovt) [reply schematics/ng-add/dependencies.ts:42]: You're right. Do you think it makes sense to check whether the version exists using the NPM API?

Comment (joeldenning) [reply schematics/ng-add/dependencies.ts:42]: > Do you think it makes sense to check whether the version exists using the NPM API?

Yeah that could work. Alternatively, maybe we maintain a map of versions?

```js
const angularVersionToCustomWebpackVersion = {
  9: 9,
  10: 10,
  11: 10
}
```

I'm open to whichever approach is most accurate and maintainable

Comment (arturovt) [reply schematics/ng-add/dependencies.ts:42]: Umm, I'm just afraid that we will need to change that map and publish new versions.

Comment (joeldenning) [reply schematics/ng-add/dependencies.ts:42]: Agreed - that would be unfortunate. So you're suggesting using the same major version if it exists, and falling back to `latest` otherwise? I'm okay with that, and agree it will require less maintenance.

Comment (arturovt) [reply schematics/ng-add/dependencies.ts:42]: Yeah. Just wondering how to check if the `^10` or `^11` version exists.

Comment (joeldenning) [reply schematics/ng-add/dependencies.ts:42]: Here's one way I've done it in the past: https://github.com/esm-bundle/react-dom/blob/4c485bb1f7364b870ee9ec5c09a0f966243d40a0/rollup.config.js#L57.

Comment (filoxo) [reply schematics/ng-add/dependencies.ts:42]: Another option would be to use [`npm view`](https://docs.npmjs.com/cli/v6/commands/npm-view) which we use in [create-single-spa to check if there are updates to it.](https://github.com/single-spa/create-single-spa/blob/29c27038478762430285fd289ad8372c3d0bc2ea/packages/generator-single-spa/src/generator-single-spa.js#L39)

**Review by joeldenning — APPROVED** [review]
I like the approach, nice work
